version: '2'
services:
  stack-service:
    image: founder/stack-services:1.0.0.${BUILD_NUMBER}
    stdin_open: true
    tty: true
    labels:
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
